### ISSUE TITLE
Node errors

### ISSUE THREAD

**Issue by iceblu3710** [adam-nielsen/lz2treefile#2]
What is the node dependencies to run this app? Running ` node index.js < db.cd32 > output.txt` throws errors and  node index.js` just waits for input then errors.

```
> node index.js < db.cd32 > output.txt
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:216:10)
    at SyncWriteStream.Writable.write (_stream_writable.js:245:12)
    at Object.<anonymous> (/home/uminded/Programming/ssh_hack/Database/index.js:104:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

```

**Comment by adam-nielsen** [comment]
There aren't any dependencies beyond what comes with Node itself.  Maybe you can try `console.log()` just before the error line to see what it's trying to output, as that might shed some light on why it can't output it.

Note that I've only tested it with `.cd3` files, so I'm not sure whether `.cd32` is the same format or not.

**Comment by iceblu3710** [comment]
I dumped output to the console and used tostring(). It looked like ascii
characters being output.

I tried a simple .cd3 file and the error said the input stream was too big.

Both cd3 cd32 have the same format as far as I can tell from the first
hundred bytes, just different info in what looks like jumbled json.

Do you have an example cd3 and resulting output I can use to track down my
error?

**Comment by adam-nielsen** [comment]
Here is an empty project I created with Crimson 3.0: [example.zip](https://github.com/adam-nielsen/lz2treefile/files/5916160/example.zip)

I see it didn't escape a control character right in the header so looks like the algorithm might need some refinement, however it was able to correctly decompress the rest of the file.

**Comment by iceblu3710** [comment]
With a fresh pull of the repo and using your example file I still crash. The 'output' var is not a string.

Any chance you have a slightly newer local version not pushed?

```
node index.js < empty.cd3 > output.txt
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:216:10)
    at SyncWriteStream.Writable.write (_stream_writable.js:245:12)
    at Object.<anonymous> (/home/uminded/Programming/ssh_hack/Database/index.js:104:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)


```

**Comment by adam-nielsen** [comment]
I double-checked but the code I used to produce that sample .txt file is the same as in the repo, no local changes that haven't been pushed.

What version of NodeJS are you running?  I'm using 15.6.

**Comment by iceblu3710** [comment]
Using v15.6 works. I tried v10 and v14 and it threw errors.

And it works with .cd31 and .cd32 files as well.

Thanks!

**Comment by adam-nielsen** [comment]
Interesting, guess the older versions can't output the `Uint8Array` directly, good to know.
